from typing import List
import re
from schemas import BankDocument, ValidationIssue

DUMMY_TOKENS = [
    "sample", "specimen", "template", "dummy", "placeholder"
]
PLACEHOLDER_NAMES = [
    "john a. doe", "john doe", "jane doe", "account holder name", "xxx", "xxxxx"
]
GENERIC_BANKS = [
    "your bank", "sample bank", "abc bank", "test bank", "demo bank"
]

def pdf_specific_validator(doc: BankDocument) -> List[ValidationIssue]:
    if doc.source != "pdf":
        return []
    issues: List[ValidationIssue] = []
    text = (doc.raw_text or "").lower()

    # Strong dummy/template indicators
    dummy_hits = [t for t in DUMMY_TOKENS if re.search(rf"\b{re.escape(t)}\b", text)]
    if dummy_hits:
        issues.append(ValidationIssue(
            code="PDF_DUMMY_INDICATORS",
            message=f"Dummy/template tokens detected: {', '.join(dummy_hits)}",
            severity="ERROR",
            score_impact=10.0
        ))

    # Placeholder names
    name_hits = [n for n in PLACEHOLDER_NAMES if n in text]
    if name_hits:
        issues.append(ValidationIssue(
            code="PDF_PLACEHOLDER_NAMES",
            message=f"Placeholder names present: {', '.join(name_hits)}",
            severity="WARN",
            score_impact=6.0
        ))

    # Generic bank labels
    bank_hits = [b for b in GENERIC_BANKS if b in text]
    if bank_hits:
        issues.append(ValidationIssue(
            code="PDF_GENERIC_BANK",
            message=f"Generic bank branding: {', '.join(bank_hits)}",
            severity="WARN",
            score_impact=5.0
        ))

    # Missing PDF metadata
    meta = doc.meta
    missing_meta = []
    if not meta.pdf_author: missing_meta.append("author")
    if not meta.pdf_creator: missing_meta.append("creator")
    if not meta.pdf_producer: missing_meta.append("producer")
    if missing_meta:
        issues.append(ValidationIssue(
            code="PDF_MISSING_METADATA",
            message=f"Missing PDF metadata fields: {', '.join(missing_meta)}",
            severity="INFO",
            score_impact=2.0
        ))

    # Google Docs source
    producer_concat = " ".join(filter(None, [
        meta.pdf_creator or "",
        meta.pdf_producer or ""
    ])).lower()
    if "google" in producer_concat or "docs" in producer_concat:
        issues.append(ValidationIssue(
            code="PDF_GOOGLE_DOCS_SOURCE",
            message="PDF appears generated by Google Docs.",
            severity="WARN",
            score_impact=4.0
        ))

    # Unencrypted (informational)
    if meta.pdf_encrypted is False:
        issues.append(ValidationIssue(
            code="PDF_UNENCRYPTED",
            message="PDF not encrypted (informational).",
            severity="INFO",
            score_impact=1.0
        ))
    return issues
